### ISSUE TITLE
is this related to trpc.io? 🤷‍♂️ 

### ISSUE THREAD

**Issue by daison12006013** [trpc-group/trpc#24]
I'm quite confused, why you call this tRPC?, the term tRPC already exists and that term "t" is Typescript, any reason why you call this tRPC rather than mlRPC/mRPC (multi-language RPC)

**Comment by helloopenworld** [comment]
not related to trpc.io. tRPC was created by Tencent, t stands for Tencent.

**Comment by mmkal** [comment]
You should clarify this distinction in the readme/docs (or better, change the name). trpc.io was around for years before this, so it's just going to confuse people.
