### ISSUE TITLE
app client protocol sdk

### ISSUE THREAD

**Issue by city-invoker** [trpc-group/trpc#30]
有没有适用app或页面客户端开发使用的sdk支持trpc协议的封装，有没有相关的项目已经开源或准备开源的

**Comment by helloopenworld** [comment]
目前还没有，刚好问问是需要什么平台什么语言的sdk？

**Comment by city-invoker** [comment]
THX,没啥，只是想接入个小程序测试下看看玩儿而已，伸手没有就自己撸呗
